package com.senither.hypixel.hypixel.bazaar;

public enum BazaarProduct {

    // Farming
    SEEDS("SEEDS", "Seeds"),
    ENCHANTED_SEEDS("ENCHANTED_SEEDS", "Enchanted Seeds"),
    HAY_BLOCK("HAY_BLOCK", "Hay Block"),
    ENCHANTED_HAY_BLOCK("ENCHANTED_HAY_BLOCK", "Enchanted Hay Block"),
    BROWN_MUSHROOM("BROWN_MUSHROOM", "Brown Mushroom"),
    RED_MUSHROOM("RED_MUSHROOM", "Red Mushroom"),
    ENCHANTED_RED_MUSHROOM("ENCHANTED_RED_MUSHROOM", "Enchanted Red Mushroom"),
    ENCHANTED_BROWN_MUSHROOM("ENCHANTED_BROWN_MUSHROOM", "Enchanted Brown Mushroom"),
    BROWN_MUSHROOM_BLOCK("HUGE_MUSHROOM_1", "Brown Mushroom Block"),
    RED_MUSHROOM_BLOCK("HUGE_MUSHROOM_2", "Red Mushroom Block"),
    ENCHANTED_BROWN_MUSHROOM_BLOCK("ENCHANTED_HUGE_MUSHROOM_1", "Enchanted Brown Mushroom Block"),
    ENCHANTED_RED_MUSHROOM_BLOCK("ENCHANTED_HUGE_MUSHROOM_2", "Enchanted Red Mushroom Block"),
    COCOA_BEANS("INK_SACK:3", "Coco Beans"),
    ENCHANTED_COCOA("ENCHANTED_COCOA", "Enchanted Coco Bean"),
    ENCHANTED_COOKIE("ENCHANTED_COOKIE", "Enchanted Cookie"),
    CARROT_ITEM("CARROT_ITEM", "Carrot"),
    ENCHANTED_CARROT("ENCHANTED_CARROT", "Enchanted Carrot"),
    ENCHANTED_CARROT_ON_A_STICK("ENCHANTED_CARROT_STICK", "Enchanted Carrot on a Stick"),
    ENCHANTED_GOLDEN_CARROT("ENCHANTED_GOLDEN_CARROT", "Enchanted Golden Carrot"),
    POTATO_ITEM("POTATO_ITEM", "Potato"),
    ENCHANTED_POTATO("ENCHANTED_POTATO", "Enchanted Potato"),
    ENCHANTED_BAKED_POTATO("ENCHANTED_BAKED_POTATO", "Enchanted Baked Potato"),
    RABBIT("RABBIT", "Rabbit"),
    ENCHANTED_RABBIT("ENCHANTED_RABBIT", "Enchanted Rabbit"),
    RABBIT_HIDE("RABBIT_HIDE", "Rabbit Hide"),
    ENCHANTED_RABBIT_FOOT("ENCHANTED_RABBIT_FOOT", "Enchanted Rabbit Foot"),
    ENCHANTED_RABBIT_HIDE("ENCHANTED_RABBIT_HIDE", "Enchanted Rabbit Hide"),
    MELON("MELON", "Melon"),
    ENCHANTED_MELON("ENCHANTED_MELON", "Enchanted Melon"),
    ENCHANTED_MELON_BLOCK("ENCHANTED_MELON_BLOCK", "Enchanted Melon Block"),
    ENCHANTED_GLISTERING_MELON("ENCHANTED_GLISTERING_MELON", "Enchanted Glistering Melon"),
    SUGAR_CANE("SUGAR_CANE", "Sugarcane"),
    ENCHANTED_PAPER("ENCHANTED_PAPER", "Enchanted Paper"),
    ENCHANTED_SUGAR("ENCHANTED_SUGAR", "Enchanted Sugar"),
    ENCHANTED_SUGAR_CANE("ENCHANTED_SUGAR_CANE", "Enchanted Sugarcane"),
    CACTUS("CACTUS", "Cactus"),
    ENCHANTED_CACTUS("ENCHANTED_CACTUS", "Enchanted Cactus"),
    ENCHANTED_CACTUS_GREEN("ENCHANTED_CACTUS_GREEN", "Enchanted Cactus Green"),
    ENCHANTED_EGG("ENCHANTED_EGG", "Enchanted Egg"),
    SUPER_EGG("SUPER_EGG", "Enchanted Super Egg"),
    ENCHANTED_CAKE("ENCHANTED_CAKE", "Enchanted Cake"),
    PUMPKIN("PUMPKIN", "Pumpkin"),
    ENCHANTED_PUMPKIN("ENCHANTED_PUMPKIN", "Enchanted Pumpkin"),
    WHEAT("WHEAT", "Wheat"),
    ENCHANTED_BREAD("ENCHANTED_BREAD", "Enchanted Bread"),
    MUTTON("MUTTON", "Mutton"),
    ENCHANTED_MUTTON("ENCHANTED_MUTTON", "Enchanted Mutton"),
    ENCHANTED_COOKED_MUTTON("ENCHANTED_COOKED_MUTTON", "Enchanted Cooked Mutton"),
    RAW_BEEF("RAW_BEEF", "Raw Beef"),
    ENCHANTED_RAW_BEEF("ENCHANTED_RAW_BEEF", "Enchanted Raw Beef"),
    PORK("PORK", "Pork"),
    ENCHANTED_PORK("ENCHANTED_PORK", "Enchanted Pork"),
    ENCHANTED_GRILLED_PORK("ENCHANTED_GRILLED_PORK", "Enchanted Grilled Pork"),
    RAW_CHICKEN("RAW_CHICKEN", "Raw Chicken"),
    ENCHANTED_RAW_CHICKEN("ENCHANTED_RAW_CHICKEN", "Enchanted Raw Chicken"),
    RABBIT_FOOT("RABBIT_FOOT", "Rabbit Foot"),
    LEATHER("LEATHER", "Leather"),
    ENCHANTED_LEATHER("ENCHANTED_LEATHER", "Enchanted Leather"),
    FEATHER("FEATHER", "Feather"),
    ENCHANTED_FEATHER("ENCHANTED_FEATHER", "Enchanted Feather"),

    // Mining,
    COBBLESTONE("COBBLESTONE", "Cobblestone"),
    ENCHANTED_COBBLESTONE("ENCHANTED_COBBLESTONE", "Enchanted Cobblestone"),
    ENDER_STONE("ENDER_STONE", "Ender Stone"),
    DIAMOND("DIAMOND", "Diamond"),
    ENCHANTED_DIAMOND("ENCHANTED_DIAMOND", "Enchanted Diamond"),
    ENCHANTED_DIAMOND_BLOCK("ENCHANTED_DIAMOND_BLOCK", "Enchanted Diamond Block"),
    IRON_INGOT("IRON_INGOT", "Iron Ingot"),
    ENCHANTED_IRON("ENCHANTED_IRON", "Enchanted Iron"),
    ENCHANTED_IRON_BLOCK("ENCHANTED_IRON_BLOCK", "Enchanted Iron Block"),
    GOLD_INGOT("GOLD_INGOT", "Gold Ingot"),
    ENCHANTED_GOLD("ENCHANTED_GOLD", "Enchanted Gold"),
    ENCHANTED_GOLD_BLOCK("ENCHANTED_GOLD_BLOCK", "Enchanted Gold Block"),
    REDSTONE("REDSTONE", "Redstone"),
    ENCHANTED_REDSTONE("ENCHANTED_REDSTONE", "Enchanted Redstone"),
    ENCHANTED_REDSTONE_BLOCK("ENCHANTED_REDSTONE_BLOCK", "Enchanted Redstone Block"),
    ENCHANTED_REDSTONE_LAMP("ENCHANTED_REDSTONE_LAMP", "Enchanted Redstone Lamp"),
    LAPIS_LAZULI("INK_SACK:4", "Lapis Lazuli"),
    ENCHANTED_LAPIS_LAZULI("ENCHANTED_LAPIS_LAZULI", "Enchanted Lapis Lazuli"),
    ENCHANTED_LAPIS_LAZULI_BLOCK("ENCHANTED_LAPIS_LAZULI_BLOCK", "Enchanted Lapis Lazuli Block"),
    EMERALD("EMERALD", "Emerald"),
    ENCHANTED_EMERALD("ENCHANTED_EMERALD", "Enchanted Emerald"),
    ENCHANTED_EMERALD_BLOCK("ENCHANTED_EMERALD_BLOCK", "Enchanted Emerald Block"),
    OBSIDIAN("OBSIDIAN", "Obsidian"),
    ENCHANTED_OBSIDIAN("ENCHANTED_OBSIDIAN", "Enchanted Obsidian"),
    COAL("COAL", "Coal"),
    ENCHANTED_COAL("ENCHANTED_COAL", "Enchanted Coal"),
    ENCHANTED_CHARCOAL("ENCHANTED_CHARCOAL", "Enchanted Charcoal"),
    ENCHANTED_COAL_BLOCK("ENCHANTED_COAL_BLOCK", "Enchanted Coal Block"),
    GRAVEL("GRAVEL", "Gravel"),
    FLINT("FLINT", "Flint"),
    GLOWSTONE_DUST("GLOWSTONE_DUST", "Glowstone Dust"),
    ENCHANTED_GLOWSTONE_DUST("ENCHANTED_GLOWSTONE_DUST", "Enchanted Glowstone Dust"),
    ENCHANTED_GLOWSTONE("ENCHANTED_GLOWSTONE", "Enchanted Glowstone Block"),
    ENCHANTED_FLINT("ENCHANTED_FLINT", "Enchanted Flint"),
    ICE("ICE", "Ice"),
    ENCHANTED_ICE("ENCHANTED_ICE", "Enchanted Ice"),
    PACKED_ICE("PACKED_ICE", "Packed Ice"),
    ENCHANTED_PACKED_ICE("ENCHANTED_PACKED_ICE", "Enchanted Packed Ice"),
    SNOW_BALL("SNOW_BALL", "Snow Ball"),
    SNOW_BLOCK("SNOW_BLOCK", "Snow Block"),
    ENCHANTED_SNOW_BLOCK("ENCHANTED_SNOW_BLOCK", "Enchanted Snow Block"),
    ENCHANTED_ENDSTONE("ENCHANTED_ENDSTONE", "Enchanted Endstone"),
    SAND("SAND", "Sand"),
    ENCHANTED_SAND("ENCHANTED_SAND", "Enchanted Sand"),
    NETHERRACK("NETHERRACK", "Netherrack"),
    NETHER_STALK("NETHER_STALK", "Enchanted Nether Stalk"),
    ENCHANTED_NETHER_STALK("ENCHANTED_NETHER_STALK", "Enchanted Nether Stalk"),
    QUARTZ("QUARTZ", "Quartz"),
    ENCHANTED_QUARTZ("ENCHANTED_QUARTZ", "Enchanted Quartz"),
    ENCHANTED_QUARTZ_BLOCK("ENCHANTED_QUARTZ_BLOCK", "Enchanted Quartz Block"),
    ENCHANTED_LAVA_BUCKET("ENCHANTED_LAVA_BUCKET", "Enchanted Lava Bucket"),

    // Combat
    STRING("STRING", "String"),
    ENCHANTED_STRING("ENCHANTED_STRING", "Enchanted String"),
    ENDER_PEARL("ENDER_PEARL", "Ender Pearl"),
    ENCHANTED_ENDER_PEARL("ENCHANTED_ENDER_PEARL", "Enchanted Ender Pearl"),
    ENCHANTED_EYE_OF_ENDER("ENCHANTED_EYE_OF_ENDER", "Enchanted Eye of Ender"),
    BONE("BONE", "Bone"),
    ENCHANTED_BONE("ENCHANTED_BONE", "Enchanted Bone"),
    ROTTEN_FLESH("ROTTEN_FLESH", "Rotten Flesh"),
    ENCHANTED_ROTTEN_FLESH("ENCHANTED_ROTTEN_FLESH", "Enchanted Rotten Flesh"),
    SLIME_BALL("SLIME_BALL", "Slime Ball"),
    ENCHANTED_SLIME_BALL("ENCHANTED_SLIME_BALL", "Enchanted Slime Ball"),
    ENCHANTED_SLIME_BLOCK("ENCHANTED_SLIME_BLOCK", "Enchanted Slime Block"),
    SULPHUR("SULPHUR", "Gunpowder"),
    ENCHANTED_GUNPOWDER("ENCHANTED_GUNPOWDER", "Enchanted Gunpowder"),
    ENCHANTED_FIREWORK_ROCKET("ENCHANTED_FIREWORK_ROCKET", "Enchanted Firework Rocket"),
    BLAZE_ROD("BLAZE_ROD", "Blaze Rod"),
    ENCHANTED_BLAZE_POWDER("ENCHANTED_BLAZE_POWDER", "Enchanted Blaze Powder"),
    ENCHANTED_BLAZE_ROD("ENCHANTED_BLAZE_ROD", "Enchanted Blaze Rod"),
    SPIDER_EYE("SPIDER_EYE", "Spider Eye"),
    ENCHANTED_SPIDER_EYE("ENCHANTED_SPIDER_EYE", "Enchanted Spider Eye"),
    ENCHANTED_FERMENTED_SPIDER_EYE("ENCHANTED_FERMENTED_SPIDER_EYE", "Enchanted Fermented Spider Eye"),
    GHAST_TEAR("GHAST_TEAR", "Ghast Tear"),
    ENCHANTED_GHAST_TEAR("ENCHANTED_GHAST_TEAR", "Enchanted Ghast Tear"),
    MAGMA_CREAM("MAGMA_CREAM", "Magma Cream"),
    ENCHANTED_MAGMA_CREAM("ENCHANTED_MAGMA_CREAM", "Enchanted Magma Cream"),

    // Wood,
    OAK("LOG", "Oak Log"),
    ENCHANTED_OAK_LOG("LOG", "Enchanted Oak Log"),
    BIRCH("LOG:2", "Birch Log"),
    ENCHANTED_BIRCH_LOG("ENCHANTED_BIRCH_LOG", "Enchanted Birch Log"),
    ACACIA("LOG_2", "Acacia Log"),
    ENCHANTED_ACACIA_LOG("ENCHANTED_ACACIA_LOG", "Enchanted Acacia Log"),
    JUNGLE("LOG:3", "Jungle Log"),
    ENCHANTED_JUNGLE_LOG("ENCHANTED_JUNGLE_LOG", "Enchanted Jungle Log"),
    DARK_OAK("LOG_2:1", "Dark Oak Log"),
    ENCHANTED_DARK_OAK_LOG("ENCHANTED_DARK_OAK_LOG", "Enchanted Dark Oak Log"),
    SPRUCE("LOG:1", "Spruce Log"),
    ENCHANTED_SPRUCE_LOG("ENCHANTED_SPRUCE_LOG", "Enchanted Spruce Log"),

    // Fishing
    INK_SACK("INK_SACK", "Ink Sack"),
    ENCHANTED_INK_SACK("ENCHANTED_INK_SACK", "Enchanted Ink Sack"),
    RAW_FISH("RAW_FISH", "Raw Fish"),
    ENCHANTED_RAW_FISH("ENCHANTED_RAW_FISH", "Enchanted Raw Fish"),
    ENCHANTED_COOKED_FISH("ENCHANTED_COOKED_FISH", "Enchanted Cooked Fish"),
    RAW_SALMON("RAW_FISH:1", "Raw Salmon"),
    ENCHANTED_COOKED_SALMON("ENCHANTED_COOKED_SALMON", "Enchanted Cooked Salmon"),
    ENCHANTED_PUFFERFISH("ENCHANTED_PUFFERFISH", "Enchanted Pufferfish"),
    ENCHANTED_RAW_SALMON("ENCHANTED_RAW_SALMON", "Enchanted Raw Salmon"),
    PRISMARINE_SHARD("PRISMARINE_SHARD", "Prismarine Shard"),
    ENCHANTED_PRISMARINE_SHARD("ENCHANTED_PRISMARINE_SHARD", "Enchanted Prismarine Shard"),
    PRISMARINE_CRYSTALS("PRISMARINE_CRYSTALS", "Prismarine Crystal"),
    ENCHANTED_PRISMARINE_CRYSTALS("ENCHANTED_PRISMARINE_CRYSTALS", "Enchanted Prismarine Crystal"),
    SPONGE("SPONGE", "Sponge"),
    ENCHANTED_SPONGE("ENCHANTED_SPONGE", "Enchanted Sponge"),
    ENCHANTED_WET_SPONGE("ENCHANTED_WET_SPONGE", "Enchanted Wet Sponge"),
    PUFFERFISH("RAW_FISH:3", "Pufferfish"),
    CLONFISH("RAW_FISH:2", "Clownfish"),
    ENCHANTED_CLOWNFISH("ENCHANTED_CLOWNFISH", "Enchanted Clownfish"),
    WATER_LILY("WATER_LILY", "Lilypad"),
    ENCHANTED_WATER_LILY("ENCHANTED_WATER_LILY", "Enchanted Lilypad"),
    CLAY_BALL("CLAY_BALL", "Clay"),
    ENCHANTED_CLAY_BALL("ENCHANTED_CLAY_BALL", "Enchanted Clay"),

    // Misc
    STOCK_OF_STONKS("STOCK_OF_STONKS", "Stocks of Stonks"),
    GREEN_CANDY("GREEN_CANDY", "Green Candy"),
    PURPLE_CANDY("PURPLE_CANDY", "Purple Candy"),
    WHITE_GIFT("WHITE_GIFT", "White Gift"),
    GREEN_GIFT("GREEN_GIFT", "Green Gift"),
    RED_GIFT("RED_GIFT", "Red Gift"),
    CATALYST("CATALYST", "Catalyst"),
    HAMSTER_WHEEL("HAMSTER_WHEEL", "Hamster Wheel"),
    HOT_POTATO_BOOK("HOT_POTATO_BOOK", "Hot Potato Book"),
    TARANTULA_WEB("TARANTULA_WEB", "Tarantula Web"),
    TARANTULA_SILK("TARANTULA_SILK", "Tarantula Silk"),
    WOLF_TOOTH("WOLF_TOOTH", "Wolf Tooth"),
    GOLDEN_TOOTH("GOLDEN_TOOTH", "Golden Tooth"),
    FOUL_FLESH("FOUL_FLESH", "Foul Flesh"),
    REVENANT_FLESH("REVENANT_FLESH", "Revenant Flesh"),
    REVENANT_VISCERA("REVENANT_VISCERA", "Revenant Viscera"),
    COMPACTOR("COMPACTOR", "Compactor"),
    SUPER_COMPACTOR_3000("SUPER_COMPACTOR_3000", "Super Compactor 3000"),
    PROTECTOR_FRAGMENT("PROTECTOR_FRAGMENT", "Protector Fragment"),
    OLD_FRAGMENT("OLD_FRAGMENT", "Old Fragment"),
    WISE_FRAGMENT("WISE_FRAGMENT", "Wise Fragment"),
    STRONG_FRAGMENT("STRONG_FRAGMENT", "Strong Fragment"),
    YOUNG_FRAGMENT("YOUNG_FRAGMENT", "Young Fragment"),
    UNSTABLE_FRAGMENT("UNSTABLE_FRAGMENT", "Unstable Fragment"),
    SUPERIOR_FRAGMENT("SUPERIOR_FRAGMENT", "Superior Fragment"),
    SUMMONING_EYE("SUMMONING_EYE", "Summoning Eye");

    private final String key;
    private final String name;

    BazaarProduct(String key, String name) {
        this.key = key;
        this.name = name;
    }

    public String getKey() {
        return key;
    }

    public String getName() {
        return name;
    }

    public static BazaarProduct getFromKey(String key) {
        for (BazaarProduct product : values()) {
            if (product.getKey().equalsIgnoreCase(key)) {
                return product;
            }
        }
        return null;
    }
}
