<template>
    <fullscreen-hero-status
        v-if="stage == stages.LOADING_REPORT"
        :title="'Loading guild scan report'"
        :subtitle="`Report ID: <i>${id}</i>`"
        :note="'<p class=\'button is-loading\' />'"
    />

    <fullscreen-hero-status
        v-else-if="stage == stages.GENERATING_REPORT"
        :title="'Generating guild report'"
        :subtitle="`
            Guild scan report is still being generated by the bot!
            <br>${reportStage.completed} out of ${reportStage.completed + reportStage.pending} people have been scanned, estimated ${pendingTimeLeft} remaining!
        `"
        :note="`Retrying in <i>${countdown}</i> seconds.`"
    />

    <fullscreen-hero-status
        v-else-if="stage == stages.INVALID_ID"
        :title="'Failed to load guild scan report'"
        :subtitle="`Invalid report ID provided!`"
    />

    <fullscreen-hero-status
        v-else-if="stage == stages.NOT_FOUND"
        :title="'Report was not found!'"
        :subtitle="`No guild scan report were found with an ID of <i>${id}</i>!`"
        :note="`Retrying in <i>${countdown}</i> seconds.`"
    />

    <fullscreen-hero-status
        v-else
        :title="'Failed to load report'"
        :subtitle="'The server responded with an unknown error!'"
        :note="`Retrying in <i>${countdown}</i> seconds.`"
    />
</template>

<style lang="scss">
    .button.is-loading {
        font-size: 8em;
        border-color: rgba(0, 0, 0, 0);
        background-color: rgba(0, 0, 0, 0);
    }
</style>

<script>
    import moment from 'moment';
    import config from '../config';
    import FullscreenHeroStatus from '../components/FullscreenHeroStatus';

    export default {
        props: {
            id: String
        },
        components: {
            FullscreenHeroStatus
        },
        mounted() {
            this.stage = this.isUuid(this.id)
                ? this.stages.LOADING_REPORT
                : this.stages.INVALID_ID;

            if (this.stage == this.stages.LOADING_REPORT) {
                this.loadReport();
            }
        },
        data() {
            return {
                stage: null,
                reportStage: {},
                stages: {
                    LOADING_REPORT: 0,
                    GENERATING_REPORT: 1,
                    NOT_FOUND: 7,
                    INVALID_ID: 8,
                    HAS_ERROR: 9,
                },
                countdown: 0,
                countdownTaskId: null,
            };
        },
        methods: {
            loadReport() {
                axios.get(`${config.interalApi}/report/${this.id}`).then(response => {
                    if (response.data.hasOwnProperty('data')) {
                        this.reportStage = response.data.data;
                    }

                    if (response.status == 206) {
                        this.startCountdown();
                        return this.stage = this.stages.GENERATING_REPORT;
                    }

                    let report = response.data.data;

                    this.$emit('loaded-report', { report });
                }).catch(error => {
                    console.error(error);

                    this.stage = this.isNotFoundError(error)
                        ? this.stages.NOT_FOUND
                        : this.stage.HAS_ERROR;

                    this.startCountdown(60);
                });
            },
            startCountdown(timeInSeconds = 30) {
                this.countdown = timeInSeconds;
                this.countdownTaskId = setInterval(() => {
                    this.countdown--;
                    if (this.countdown < 1) {
                        clearInterval(this.countdownTaskId);
                        this.stage = this.stages.LOADING_REPORT;
                        this.loadReport();
                    }
                }, 1000);
            },
            isNotFoundError(error) {
                return error != null
                    && error.hasOwnProperty('response')
                    && error.response != undefined
                    && error.response.hasOwnProperty('status')
                    && error.response.status == 404;
            },
            isUuid(uuid) {
                return uuid.match(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$/i) != null;
            }
        },
        computed: {
            pendingTimeLeft() {
                return moment
                    .duration(this.reportStage.pending * 5, 'seconds')
                    .humanize();
            }
        }
    }
</script>
